language: java

sudo: false

jdk:
  - oraclejdk11

cache:
  directories:
    - .autoconf
    - $HOME/.m2

notifications:
  email:
    recipients:
      - vladislav.96@mail.ru
    on_success: never
    on_failure: always

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN="6745aad4-a7d7-4d67-9fab-04094cecc618"

services:
  - postgresql