CREATE DATABASE TODO;

create table todos
(
    id          int4 generated by default as identity,
    created     timestamp,
    description varchar(255),
    done        boolean not null,
    primary key (id)
)