CREATE DATABASE TODO;

create table todos
(
    id          int4 generated by default as identity,
    created     timestamp,
    description varchar(255),
    done        boolean not null,
    author_id   int     not null references t_user (id),
    primary key (id)
);


CREATE TABLE t_users
(
    id       SERIAL PRIMARY KEY,
    email    TEXT NOT NULL UNIQUE,
    name     TEXT NOT NULL,
    password TEXT NOT NULL
    --role_id  int  not null references t_role (id)
);